spring:
  datasource:
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:videotecha}
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: create-drop
