spring:
  datasource:
    username: ${POSTGRES_USER:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:videotecha}
    driverClassName: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:postgres}
  flyway:
    schemas: videotecha
